### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by websec123** [grayddq/PublicMonitors#6]
运行时显示root@test:~/PublicMonitors# python3 PublicMonitors.py
Traceback (most recent call last):
  File "PublicMonitors.py", line 3, in <module>
    from lib.Main import *
  File "/root/PublicMonitors/lib/Main.py", line 2, in <module>
    from publicScan import *
ModuleNotFoundError: No module named 'publicScan'
是什么情况呢

**Comment by blockchainguard** [comment]
要使用 python2
